### ISSUE TITLE
_catalog Endpoint Gives "invalid path"

### ISSUE THREAD

**Issue by afrazkhan** [docker/distribution-library-image#30] opened 2016-11-09 13:30 UTC
I'm running this with:

```
docker run \
  --name=docker \
  -d \
  -e DEBUG=True \
  -e LOGLEVEL=debug \
  -e REGISTRY_STORAGE_S3_BUCKET="my_bucket" \
  -e REGISTRY_STORAGE=s3 \
  -e SETTINGS_FLAVOR=s3 \
  -e REGISTRY_STORAGE_S3_REGION="eu-west-1" \
  -e REGISTRY_STORAGE_S3_ROOTDIRECTORY="/" \
  -e SEARCH_BACKEND=sqlalchemy \
  -e REGISTRY_HTTP_TLS_CERTIFICATE="/path/to/my_cert.crt" \
  -e REGISTRY_HTTP_TLS_KEY="/path/to/my_key.key" \
  -e REGISTRY_AUTH_HTPASSWD_REALM=secure \
  -e REGISTRY_AUTH_HTPASSWD_PATH="my_auth_file" \
  -v /host/path/to/certs:/path/to/certs \
  -v /host/path/to/password_file:/path/to/password_file \
  -p 443:5000 \
  registry
```

This has all been working great, except for the `_catalog` endpoint which results in:

```
invalid path: /docker/registry/v2/repositories/" err.message="unknown error"
```

That path certainly exists in my bucket (I don't think the registry would be working if it wasn't). I've tried changing the `REGISTRY_STORAGE_S3_ROOTDIRECTORY` to various paths, and setting `STORAGE_PATH` too.

**Comment by stevvooe** [comment] 2017-01-10 19:33
Duplicate of docker/distribution#2119.

**Closed by stevvooe** 2017-01-10 19:33 UTC
